booksBazaar/Sell/urls.py
from django.urls import path
from . import views


app_name = 'Sell'
urlpatterns = [

      path('', views.post_list, name='post_list'),
      path('<int:id>/',views.post_detail,name='post_detail'),
    path('create/', views.post_create, name='post_create'),
     path('<int:id>/edit',views.post_update,name='post_update'),
        path('<int:id>/delete/', views.post_delete, name='post_delete'),


]

booksBazaar/app1/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views


app_name='app1'



urlpatterns=[
    
    path('',views.index_page,name='index_page'),
		path('book_list/',views.book_list,name='book_list'),
	
	   
    path('book_list/<slug:category_slug>/', views.book_list, 
         name='book_list_by_category'),
    path('book_list/<int:id>/<slug:slug>/', views.book_detail,
         name='book_detail'),
		 
		 		path('register/',views.signup,name="register"),
	path('login/',auth_views.LoginView.as_view(template_name="users/login.html"),name="login"),
	path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
	path('password-reset/',

         auth_views.PasswordResetView.as_view(

             template_name='users/password_reset.html'

         ),

         name='password_reset'),
		 
		  path('password-reset/done/',

         auth_views.PasswordResetDoneView.as_view(

             template_name='users/password_reset_done.html'

         ),

         name='password_reset_done'),
		 
		  path('password-reset-confirm/<uidb64>/<token>/',

         auth_views.PasswordResetConfirmView.as_view(

             template_name='users/password_reset_confirm.html'

         ),

         name='password_reset_confirm'),
		 path('password-reset-complete/',

         auth_views.PasswordResetCompleteView.as_view(

             template_name='users/password_reset_complete.html'

         ),

         name='password_reset_complete'),
    
    
      path('search/',views.search,name='search'),
		 
	
	
	
]

booksBazaar/booksBazaar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls', namespace='app1')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('Sell/', include('Sell.urls', namespace='Sell')),

	
	
	
	
	
	
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

booksBazaar/Sell/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
	
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    img=models.ImageField(blank=True,default='c.jpg')
    description=models.TextField(blank=True)
    contact=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name='Sell_posts')
    created = models.DateTimeField(auto_now_add=True)
	
	

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('Sell:post_detail',args=[self.id])
        
        

        
        
    

	

booksBazaar/Sell/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=[
            "title",
            "img",
            
            "description",
            "contact",
            "price",
            "owner",
        ]

booksBazaar/Sell/views.py
from .forms import PostForm
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404,redirect
from .models import Post


def post_list(request):
    posts = Post.objects.all()
    return render(request,'Sell/index.html',{'posts': posts})
		

def post_detail(request, id=None):
    post = get_object_or_404(Post,id=id)
    return render(request,'Sell/detail.html',{'post': post})

def post_create(request):
    form=PostForm(request.POST or None)
    if form.is_valid():
        post=form.save(commit=False)
        post.save()
        return HttpResponseRedirect(post.get_absolute_url())
        
    
        
    context={"form":form,}
    return render(request,"Sell/post_form.html",context)

def post_update(request,id=None):
    post = get_object_or_404(Post,id=id)
    form=PostForm(request.POST or None,instance=post)
    if form.is_valid():
        post=form.save(commit=False)
        post.save()
        return HttpResponseRedirect(post.get_absolute_url())
    
        
    context={"form":form,}
    return render(request,"Sell/post_form.html",context)






def post_delete(request,id=None):
    post = get_object_or_404(Post,id=id)
    post.delete()
    return redirect('Sell:post_list')
    
        
    context={"form":form,}
    return render(request,"Sell/post_form.html",context)

booksBazaar/Sell/templates/Sell/detail.html
{% extends 'app1/base.html' %}
 {% load static %}
{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}
{% block content %}

 <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    <li><a href="{% url 'app1:book_list' %}">BOOKS</a></li>
                    
                     <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                    <li><a href="{% url 'app1:login' %}">LOGIN</a></li>

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>


<br><br>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <div class="con">






<div class="cont">
  {% if post.img %}
            
			<div class="sellimg">
			
                   <a href="{{ post.get_absolute_url }}" > <img   class="imk " src='{{ post.img.url }}' width="400"  /></a>
					
					</div>
					
					{% endif %}
					
					
					<div class="selldetails">
					
					
					
					<div class="title">
					    {{ post.title }}
						</div>
	<div class="created">
	{{ post.created }}

    </div>
	
	
	<div class="description">
	{{ post.description }}

    </div>
         <div class="contact">        

 Contact Details :	  
{{ post.contact}}

       </div>         
<div class="price">
Price:
Rs. {{post.price}}
    </div>
	
	<div class="owner">
	Owner:
 {{ post.owner }}
					
		</div>	
		<br>

<div class="mod">


<a  class="modi" href="{% url 'Sell:post_update' post.id %}">Update</a>



<a class="modi" href="{% url 'Sell:post_delete' post.id %}">Delete</a>

</div>	


	
					
		</div>			
		
			
					
				
					














  

 
 
  


    
    
    
    

                



 



</div>





</div>
 
 
 
 
 
 
 
 
 
 
 
 

</p>
{% endblock content %}

booksBazaar/Sell/templates/Sell/index.html
{% extends 'app1/base.html' %}
 {% load static %}
{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}
{% block content %}

 <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    <li><a href="{% url 'Sell:post_create' %}">Post an Add</a></li>
                    <li><a href="{% url 'app1:book_list' %}">BOOKS</a></li>
                    
                     <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                    <li><a href="{% url 'app1:login' %}">LOGIN</a></li>

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>
<br></br>

<div class="con">


{% for post in posts %}



<div class="cont">
  {% if post.img %}
            
			<div class="sellimg">
			
                   <a href="{{ post.get_absolute_url }}" > <img   class="imk " src='{{ post.img.url }}' width="400"  /></a>
					
					</div>
					
					{% endif %}
					
					
					<div class="selldetails">
					
					
					
					<div class="title">
					    {{ post.title }}
						</div>
	<div class="created">
	{{ post.created }}

    </div>
	
	
	<div class="description">
	{{ post.description }}

    </div>
	
      <div class="contact">        

 Contact Details :	  
{{ post.contact}}

       </div>         
<div class="price">
Price:
Rs. {{post.price}}
    </div>
	
	<div class="owner">
	Owner:
 {{ post.owner }}
					
		</div>			
					
		</div>			
		
			
					
				
					














  

 
 
  


    
    
    
    

                



 



</div>
{% endfor %}




</div>



{% endblock content %}

booksBazaar/Sell/templates/Sell/post_form.html
{% extends 'app1/base.html' %}
 {% load static %}
{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}
{% block content %}




 <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    <li><a href="{% url 'app1:book_list' %}">BOOKS</a></li>
                    
                     <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                    <li><a href="#">LOGIN</a></li>

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>





<div class="chkout">

<form class="fmda" method='post' enctype='multipart/form-data'>

<center><h2>Post An Add</h2></center>
<br>
{% csrf_token %}
{% for field in form %}
     
       <div>
      <label class="head"> {{ field.label }}</label><br>
       {{ field }}<br><br>
       {% for error in field.errors %}
         <p style="color: red">{{ error }}</p>
       {% endfor %}
     </div>
     
   {% endfor %}
   

<center><button class="adp" type="submit">Add Product</button></center>
    
</form>


</div>














{% endblock %}