booksBazaar/Sell/urls.py
from django.urls import path
from . import views


app_name = 'Sell'
urlpatterns = [

      path('', views.post_list, name='post_list'),
      path('<int:id>/',views.post_detail,name='post_detail'),
    path('create/', views.post_create, name='post_create'),
     path('<int:id>/edit',views.post_update,name='post_update'),
        path('<int:id>/delete/', views.post_delete, name='post_delete'),


]

booksBazaar/app1/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views


app_name='app1'



urlpatterns=[
    
    path('',views.index_page,name='index_page'),
		path('book_list/',views.book_list,name='book_list'),
	
	   
    path('book_list/<slug:category_slug>/', views.book_list, 
         name='book_list_by_category'),
    path('book_list/<int:id>/<slug:slug>/', views.book_detail,
         name='book_detail'),
		 
		 		path('register/',views.signup,name="register"),
	path('login/',auth_views.LoginView.as_view(template_name="users/login.html"),name="login"),
	path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
	path('password-reset/',

         auth_views.PasswordResetView.as_view(

             template_name='users/password_reset.html'

         ),

         name='password_reset'),
		 
		  path('password-reset/done/',

         auth_views.PasswordResetDoneView.as_view(

             template_name='users/password_reset_done.html'

         ),

         name='password_reset_done'),
		 
		  path('password-reset-confirm/<uidb64>/<token>/',

         auth_views.PasswordResetConfirmView.as_view(

             template_name='users/password_reset_confirm.html'

         ),

         name='password_reset_confirm'),
		 path('password-reset-complete/',

         auth_views.PasswordResetCompleteView.as_view(

             template_name='users/password_reset_complete.html'

         ),

         name='password_reset_complete'),
    
    
      path('search/',views.search,name='search'),
		 
	
	
	
]

booksBazaar/booksBazaar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls', namespace='app1')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('Sell/', include('Sell.urls', namespace='Sell')),

	
	
	
	
	
	
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

booksBazaar/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:book_id>/',
         views.cart_remove,
         name='cart_remove'),
]

booksBazaar/app1/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
	name=models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200,unique=True)
	def __str__(self):
		return self.name
    
	def get_absolute_url(self):
		return reverse('app1:book_list_by_category',args=[self.slug])
    
class Book(models.Model):
	name=models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	category=models.ForeignKey(Category,on_delete=models.CASCADE)
	image=models.ImageField()
	description=models.TextField(blank=True)
	price=models.DecimalField(max_digits=10,decimal_places=2)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)
	
	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)
    
	def __str__(self):
		return self.name
		
	def get_absolute_url(self):
		return reverse('app1:book_detail',args=[self.id, self.slug])

booksBazaar/app1/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email',)
		
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email',)
		

		
		

booksBazaar/app1/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm

from .models import *

from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.db.models import Q



def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			username= form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username,email=user.email, password=raw_password)
			login(request, user)
			messages.success(request,f'Account created')
			return redirect('app1:login')
	else:
		form = SignUpForm()
	return render(request, 'users/register.html', {'form': form})

	



def search(request):

    if request.method=='POST':
        srch=request.POST['srh']
        if srch:
            match=Book.objects.filter(Q(name__icontains=srch))
            if match:
                return render(request,'users/search.html',{'sr':match})
        else:
            return HttpResponseRedirect('/search/')
    return render(request,'users/search.html')



def index_page(request):
    return render(request, 'app1/books/index.html')
	

	

def book_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    books = Book.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        books = books.filter(category=category)
    return render(request,
                  'app1/books/book_list.html',
                  {'category': category,
                   'categories': categories,
                   'books': books})


def book_detail(request, id, slug):
    book = get_object_or_404(Book,
                                id=id,
                                slug=slug
                                )
    cart_product_form = CartAddProductForm()
    return render(request,
                  'app1/books/book_detail.html',
                  {'book': book,'cart_product_form': cart_product_form
                   })

booksBazaar/app1/templates/app1/books/book_detail.html
{% extends "app1/base.html" %}
{% load static %}

{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}

{% block content %}

   <div class="book-nav">
		  
		  <a href="{% url 'app1:index_page' %}"> <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                  
                    
                   <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                   {% if request.user.is_authenticated %}

					<li><a href="{% url 'app1:logout' %}">LOGOUT</a></li>
					
					{%else%}
					<li><a href="{% url 'app1:login' %}">LOGIN</a></li>
					{% endif %}

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>







  <div class="book-detail">
    <img src="{{book.image.url}}">
    <h1>{{ book.name }}</h1>
	<br>
    <a href="{{ book.category.get_absolute_url }}">{{ book.category }}</a>

    <p class="price">Rs. {{ book.price }}</p>
	
	<br>
	  {{ book.description }}
	  <br>
	  <br>
  <form action="{% url 'cart:cart_add' book.id %}" method="post">

 {{ cart_product_form }}
 {% csrf_token %}
 <input class="atc" type="submit" value="Add to cart">
</form>
  
  </div>
{% endblock %}

booksBazaar/app1/templates/app1/books/book_list.html
{% extends "app1/base.html" %}
 {% load static %}
{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}
{% block content %} 
      
          <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    
                    
                    <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                    {% if request.user.is_authenticated %}
					
					<li><a href="{% url 'app1:logout' %}">LOGOUT</a></li>
                    
					
					{%else%}
					<li><a href="{% url 'app1:login' %}">LOGIN</a></li>
					{% endif %}
                </ul>
		  
		  
		  
		  
		  
		  
		  </div>



<br>

        
<div id="bo-container">
 <div id="sidebar">
    <h3>Categories</h3>
	<br>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'app1:book_list' %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="book-list">
    <h1 class="her">{% if category %}{{ category.name }}{% else %}Books{% endif %}</h1>
    {% for book in books %}
      <div class="item">
        <a href="{{ book.get_absolute_url }}">
          <img  src="{{book.image.url}}" >
     

	   </a>
        <a href="{{ book.get_absolute_url }}">{{ book.name }}</a><br>
        Rs.{{ book.price }}
		
      </div>
    {% endfor %}
  </div>

 </div>
 {% endblock %}

booksBazaar/app1/templates/app1/books/index.html
{% extends 'app1/base.html'%}
{% load static %}
{% block css%}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
{% endblock css%}

{% block content %}
    <header>

        <nav>
            <div class="row">

              <a href="{% url 'app1:index_page' %}"> <img class="logo" src="{% static 'images/logo.png'%}"></a>
                
				 
				<div class="container">
        
                          
                <form method="post" action='/search/'>
{% csrf_token %}
                    
        <input class="search-input" name="srh" type="text" placeholder="Search here">
           
                    <button class=newbutton type=submit href="{% url 'app1:search' %}"> <i class="fa fa-search " id="sr"></i></button>
                    </form>
                    
  
    

  



</form>    
                    
                    
                    
                    
                    
                    
        </div>
				<ul class="main-nav" id="check">
				
                    <li><a href="{% url 'app1:book_list' %}">BOOKS</a></li>
                    
                    <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
					{% if request.user.is_authenticated %}
					
					<li><a href="{% url 'app1:logout' %}">LOGOUT</a></li>
					
					{%else%}
					<li><a href="{% url 'app1:login' %}">LOGIN</a></li>
					{% endif %}
                </ul>

                <a href="#" class="mobile-icon" onclick="slideshow()"><i class="fa fa-bars"></i></a>

            </div>





        </nav>


        
        
        
       


    </header>



<main>

<div class="div1">
    <div class="sell">
    <h1>Sell Textbooks</h1>
        <br>
    <div class='sell-text'>There's no point keeping those old textbooks around to gather dust.
    Sell your textbooks to students who need them and make some extra cash to spend on the finer
        things in life.</div></div>
    </div>
<div class="div2">
    
    <div class="div2img">
    <img class='div2img2' src="{% static 'images/2.jpg' %}"/>
    
    </div>
    
    
    </div>
<div class="div3">
    
      <div class="div2img">
    <img class='div2img2' src="{% static 'images/3.jpg' %}"/>
    
    </div>
    
    
    </div>
<div class="div4">
    
    
  


    
     <div class="sell">
    <h1>Cheap College Textbooks</h1>
        <br>
    <div class='sell-text'>Why pay full price when you don’t have to? You’re probably tired of getting gouged by your campus bookstore at this point, so save some money by buying used books from other students just like you.</div></div>
    </div>
    
    
    
<div class="div5">
    
    
      <div class="sell">
    <h1>  Price Comparison</h1>
        <br>
    <div class='sell-text'>If there’s nobody selling the textbook that you’re after on your campus, use our handy price comparison tool to find the cheapest prices online amongst 100s of stores so that you can order it quickly and avoid spending too much.</div></div>
    
    
    
  


    
    </div>
<div class="div6">
        <div class="div2img">
    <img class='div2img2' src="{% static 'images/4.jpg' %}"/>
    
    </div>
    
    </div>
<div class="div7">
    
    
    
    
    
  


        <div class="div2img">
    <img class='div2img2' src="{% static 'images/2.jpg' %}"/>
    
    </div>
    
    
    </div>
<div class="div8">
    
     <div class="sell">
    <h1>    Directly On-Campus at your College</h1>
        <br>
    <div class='sell-text'>Our service makes it easy to find used, cheap textbooks right in your own backyard. We’ll connect you with the students on your very own college campus for direct buying and selling from people just like you. No middleman, no price gouging!</div></div>
    
    
    </div>




</main>

<!--***************************************section1***************************************************-->
<div class="section">


<div class="section-area">
    
    <h1 class="section-text">Sign Up Free Today!</h1>
    <div class="section-para">When a textbook is not yet available on-campus by another student, we show you the cheapest price online amongst many bookstores.</div>
    <div class="section-search-area">
        
        
        <input class="search-input2" type="text" placeholder="Search here">
            <i class="fa fa-search " id="sr2" ></i>
        </div>
    
    </div>


</div>


<!--***************************************************************************************************-->


<!--****************************************section2*************************************************-->

<div class="section-2">


<div class="sec2text">
    <h1 class="t">Thousands and Thousands of Students Served!</h1>
    <div class="a" >And we don’t mean to brag, but we’ve saved them over</div>
    <div class="b">$116,843,431.78!</div>
    
    </div>



</div>

<!--***************************************************************************************************-->





<!--*******************************************footer**********************************************-->
<footer class="footer-distributed">

			<div class="footer-left">

				<h3 class="fthj"><a href='/'><small>BooksBajar</small></a></h3>
		

				<p class="footer-links">
					<a href="#">Home</a>
					·
					
					
					<a href="#">About</a>
					·
					
					
					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">BooksBajar &copy; 2020</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>

				</div>

			</div>

			<div class="footer-right">

				<p>Contact Us</p>

				<form action="#" method="post">

					<input type="text" name="email" placeholder="Email" />
					<textarea name="message" placeholder="Message"></textarea>
					<button>Send</button>

				</form>

			</div>

		</footer>





<div class="footer">


<div class="footer-text">
    
    <small class="cpy">Copyright &amp; 2020 all rights reserved </small>
    
    
    </div>







</div>


















<!--***************************************************************************************************-->
<!--*********************************javascript code*************************************************-->

    <script>
        function slideshow() {

            var x = document.getElementById('check');
            if (x.style.display === "none") {
                x.style.display = "block";

            } else {
                x.style.display = "none";
            }

        }
    </script>


<!--**************************************************************************************************-->





{% endblock %}