booksBazaar/Sell/urls.py
from django.urls import path
from . import views


app_name = 'Sell'
urlpatterns = [

      path('', views.post_list, name='post_list'),
      path('<int:id>/',views.post_detail,name='post_detail'),
    path('create/', views.post_create, name='post_create'),
     path('<int:id>/edit',views.post_update,name='post_update'),
        path('<int:id>/delete/', views.post_delete, name='post_delete'),


]

booksBazaar/app1/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views


app_name='app1'



urlpatterns=[
    
    path('',views.index_page,name='index_page'),
		path('book_list/',views.book_list,name='book_list'),
	
	   
    path('book_list/<slug:category_slug>/', views.book_list, 
         name='book_list_by_category'),
    path('book_list/<int:id>/<slug:slug>/', views.book_detail,
         name='book_detail'),
		 
		 		path('register/',views.signup,name="register"),
	path('login/',auth_views.LoginView.as_view(template_name="users/login.html"),name="login"),
	path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
	path('password-reset/',

         auth_views.PasswordResetView.as_view(

             template_name='users/password_reset.html'

         ),

         name='password_reset'),
		 
		  path('password-reset/done/',

         auth_views.PasswordResetDoneView.as_view(

             template_name='users/password_reset_done.html'

         ),

         name='password_reset_done'),
		 
		  path('password-reset-confirm/<uidb64>/<token>/',

         auth_views.PasswordResetConfirmView.as_view(

             template_name='users/password_reset_confirm.html'

         ),

         name='password_reset_confirm'),
		 path('password-reset-complete/',

         auth_views.PasswordResetCompleteView.as_view(

             template_name='users/password_reset_complete.html'

         ),

         name='password_reset_complete'),
    
    
      path('search/',views.search,name='search'),
		 
	
	
	
]

booksBazaar/booksBazaar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls', namespace='app1')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('Sell/', include('Sell.urls', namespace='Sell')),

	
	
	
	
	
	
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

booksBazaar/app1/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
	name=models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200,unique=True)
	def __str__(self):
		return self.name
    
	def get_absolute_url(self):
		return reverse('app1:book_list_by_category',args=[self.slug])
    
class Book(models.Model):
	name=models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	category=models.ForeignKey(Category,on_delete=models.CASCADE)
	image=models.ImageField()
	description=models.TextField(blank=True)
	price=models.DecimalField(max_digits=10,decimal_places=2)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)
	
	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)
    
	def __str__(self):
		return self.name
		
	def get_absolute_url(self):
		return reverse('app1:book_detail',args=[self.id, self.slug])

booksBazaar/app1/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email',)
		
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email',)
		

		
		

booksBazaar/app1/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm

from .models import *

from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.db.models import Q



def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			username= form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username,email=user.email, password=raw_password)
			login(request, user)
			messages.success(request,f'Account created')
			return redirect('app1:login')
	else:
		form = SignUpForm()
	return render(request, 'users/register.html', {'form': form})

	



def search(request):

    if request.method=='POST':
        srch=request.POST['srh']
        if srch:
            match=Book.objects.filter(Q(name__icontains=srch))
            if match:
                return render(request,'users/search.html',{'sr':match})
        else:
            return HttpResponseRedirect('/search/')
    return render(request,'users/search.html')



def index_page(request):
    return render(request, 'app1/books/index.html')
	

	

def book_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    books = Book.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        books = books.filter(category=category)
    return render(request,
                  'app1/books/book_list.html',
                  {'category': category,
                   'categories': categories,
                   'books': books})


def book_detail(request, id, slug):
    book = get_object_or_404(Book,
                                id=id,
                                slug=slug
                                )
    cart_product_form = CartAddProductForm()
    return render(request,
                  'app1/books/book_detail.html',
                  {'book': book,'cart_product_form': cart_product_form
                   })

booksBazaar/app1/templates/users/login.html
{% extends 'app1/base.html' %}
 {% load static %}
{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}
{% block content %}

          <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    <li><a href="{% url 'app1:book_list' %}">BOOKS</a></li>
                    <li><a href="#">BUY</a></li>
                    <li><a href="#">SELL</a></li>
                    <li><a href="#">LOGIN</a></li>

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>





<div class="loginform">
 <form class="frma" method="post">
 <div class="ltext">Login</div>
   {% csrf_token %}
   {% for field in form %}
     
       <label class="head">{{ field.label_tag }}</label>
      {{ field }}
	  <br>
	  <br>
       {% for error in field.errors %}
         <p style="color: red">{{ error }}</p>
       {% endfor %}
     
   {% endfor %}
   <button class="btn" type="submit">Sign in</button>
   
   <a class="btna"  href="{% url 'app1:register' %}">Sign Up</a>
 </form>
 
 </div>
{% endblock %}

booksBazaar/app1/templates/users/logout.html
{% extends 'app1/base.html' %}
 {% load static %}
{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}
{% block content %}

          <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    <li><a href="{% url 'app1:book_list' %}">BOOKS</a></li>
                   
                    <li><a href="#">SELL</a></li>
                    {% if request.user.is_authenticated %}

					<li><a href="{% url 'app1:logout' %}">LOGOUT</a></li>
					
					{%else%}
					<li><a href="{% url 'app1:login' %}">LOGIN</a></li>
					{% endif %}

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>

<br>
<br>
<br>
<h2 class="lgot">         You have been logged out</h2>



{% endblock %}

booksBazaar/app1/templates/users/password_reset.html
{% extends "app1/base.html" %}



{% block content %}

    <div class="content-section">

        <form method="POST">

            {% csrf_token %}

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Reset Password</legend>

                {{ form}}

            </fieldset>

            <div class="form-group">

                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>

            </div>

        </form>

    </div>

{% endblock content %}

booksBazaar/app1/templates/users/password_reset_complete.html
{% extends "app1/base.html" %}

{% block content %}

    <div class="alert alert-info">

        Your password has been set.

    </div>

    <a href="{% url 'login' %}">Sign In Here</a>

{% endblock content %}

booksBazaar/app1/templates/users/password_reset_confirm.html
{% extends "app1/base.html" %}



{% block content %}

    <div class="content-section">

        <form method="POST">

            {% csrf_token %}

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Reset Password</legend>

                {{ form }}

            </fieldset>

            <div class="form-group">

                <button class="btn btn-outline-info" type="submit">Reset Password</button>

            </div>

        </form>

    </div>

{% endblock content %}

booksBazaar/app1/templates/users/password_reset_done.html
{% extends "app1/base.html" %}

{% block content %}

    <div class="alert alert-info">

        An email has been sent with instructions to reset your password

    </div>

{% endblock content %}

booksBazaar/app1/templates/users/register.html
{% extends 'app1/base.html' %}
{% load static  %}
{% block css%}


 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}
{% block content %}

          <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    <li><a href="{% url 'app1:book_list' %}">BOOKS</a></li>
                    <li><a href="#">BUY</a></li>
                    <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                    <li><a href="{% url 'app1:login' %}">LOGIN</a></li>

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>




<div class="loginform">
 <form class="frma" method="post">
 <div class="ltext">Sign Up</div>
   {% csrf_token %}
   {% for field in form %}
     <div>
       {{ field.label_tag }}
       {{ field }}
       {% for error in field.errors %}
         <p style="color: red">{{ error }}</p>
       {% endfor %}
     </div>
   {% endfor %}
     <a class="btna"  href="{% url 'app1:login' %}">Sign in</a>
   <button class="btn" type="submit">Submit</button>
 </form>
 </div>
{% endblock %}

booksBazaar/app1/templates/users/search.html
{% extends "app1/base.html" %}
{% load static %}

{% block css%}

 <link rel="stylesheet" href="{% static 'css/book_page.css' %}" />

{% endblock css%}

{% block content %}

   <div class="book-nav">
		  
		  <a href="{% url 'app1:index_page' %}"> <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                  
                    
                   <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                   {% if request.user.is_authenticated %}

					<li><a href="{% url 'app1:logout' %}">LOGOUT</a></li>
					
					{%else%}
					<li><a href="{% url 'app1:login' %}">LOGIN</a></li>
					{% endif %}

                </ul>
		  
		  
		  
		  
		  
		  
		  </div>







  <div class="book-detail">
      
      
      
    
{% if sr %}
{% for k in sr %}

  {% if k.image %}
            <a href="{{ k.get_absolute_url }}">
                    <img src='{{k.image.url }}'   />
</a>

    

{% endif %}

{% endfor %}
{% endif %}  
      
      
      
    

  </div>







{% endblock content %}