booksBazaar/Sell/urls.py
from django.urls import path
from . import views


app_name = 'Sell'
urlpatterns = [

      path('', views.post_list, name='post_list'),
      path('<int:id>/',views.post_detail,name='post_detail'),
    path('create/', views.post_create, name='post_create'),
     path('<int:id>/edit',views.post_update,name='post_update'),
        path('<int:id>/delete/', views.post_delete, name='post_delete'),


]

booksBazaar/app1/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views


app_name='app1'



urlpatterns=[
    
    path('',views.index_page,name='index_page'),
		path('book_list/',views.book_list,name='book_list'),
	
	   
    path('book_list/<slug:category_slug>/', views.book_list, 
         name='book_list_by_category'),
    path('book_list/<int:id>/<slug:slug>/', views.book_detail,
         name='book_detail'),
		 
		 		path('register/',views.signup,name="register"),
	path('login/',auth_views.LoginView.as_view(template_name="users/login.html"),name="login"),
	path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
	path('password-reset/',

         auth_views.PasswordResetView.as_view(

             template_name='users/password_reset.html'

         ),

         name='password_reset'),
		 
		  path('password-reset/done/',

         auth_views.PasswordResetDoneView.as_view(

             template_name='users/password_reset_done.html'

         ),

         name='password_reset_done'),
		 
		  path('password-reset-confirm/<uidb64>/<token>/',

         auth_views.PasswordResetConfirmView.as_view(

             template_name='users/password_reset_confirm.html'

         ),

         name='password_reset_confirm'),
		 path('password-reset-complete/',

         auth_views.PasswordResetCompleteView.as_view(

             template_name='users/password_reset_complete.html'

         ),

         name='password_reset_complete'),
    
    
      path('search/',views.search,name='search'),
		 
	
	
	
]

booksBazaar/booksBazaar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls', namespace='app1')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('Sell/', include('Sell.urls', namespace='Sell')),

	
	
	
	
	
	
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

booksBazaar/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:book_id>/',
         views.cart_remove,
         name='cart_remove'),
]

booksBazaar/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
	   
	path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('create/', views.order_create, name='order_create'),
]

booksBazaar/cart/models.py
from django.db import models

# Create your models here.

booksBazaar/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

booksBazaar/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from app1.models import Book
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    

    
    cart_products = [item['book'] for item in cart]

    return render(request, 'cart/detail.html', {'cart': cart
                                                
                                                })

booksBazaar/cart/templates/cart/detail.html
{% load static %}
 <link rel="stylesheet" href="{% static 'css/cart.css' %}" />


{% block content %}

 <div class="book-nav">
		  
		 <a href="{% url 'app1:index_page' %}">  <img class="book-logo" src="{% static 'images/logo.png'%}"></a>
                <ul class="book-main-nav" id="book-check">
                    
                    
                    <li><a href="{% url 'Sell:post_list' %}">SELL</a></li>
                    {% if request.user.is_authenticated %}
					
					<li><a href="{% url 'app1:logout' %}">LOGOUT</a></li>
					
					{%else%}
					<li><a href="{% url 'app1:login' %}">LOGIN</a></li>
					{% endif %}
                </ul>
		  
		  
		  
		  
		  
		  
		  </div>
		  <br>
		  <br>
  <h1 class="cent">Your shopping cart</h1>
   {% with total_items=cart|length %}
 {% if total_items > 0 %}
 Your cart:
 <a href="{% url 'cart:cart_detail' %}">
 {{ total_items }} item{{ total_items|pluralize }},
 Rs.{{ cart.get_total_price }}
 </a>
 {% else %}
 Your cart is empty.
 {% endif %}
 {% endwith %}
  <br>
  <br>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
       
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.book %}
      <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/b.jpg' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
            
            <td class="num">Rs.{{ item.total_price }}</td>
			
			          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="3"></td>
        <td class="num">Rs.{{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'app1:book_list' %}" class="button light">Continue shopping</a>
   <a href="{% url 'orders:order_create' %}" class="button">
      Checkout
    </a>
	
  </p>
  
{% endblock %}